---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  annotations:
    circleci.com/project-slug: github/megianni/backstage-test
    #circleci/T1Ww4BYaubjnAKxK3fNg7N/XaXH6AivXPu1UPamMmLdrw
    #github/megianni/backstage-test
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
